version: "3"
services: 
    mysql-server:
        image: 'mysql'
        environment: 
            MYSQL_ROOT_PASSWORD: 'mysql'
        ports: 
            - "3306:3306"
    jsp-app:
        build: .
        ports: 
            - "8888:8080"